export const CURRENT_TRANSLATIONS = 'CURRENT_TRANSLATIONS';
export const SET_SETTINGS = 'SET_SETTINGS';
export const SET_SUBTITLES = 'SET_SUBTITLES';
export const SET_VIDEO_LOGO = 'SET_VIDEO_LOGO';
export const SET_VIDEO_LOGO_SIZE = 'SET_VIDEO_LOGO_SIZE';
export const SET_VIDEO_LOGO_POSITION = 'SET_VIDEO_LOGO_POSITION';
export const RESET_VIDEO_LOGO = 'RESET_VIDEO_LOGO';
